version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: 
          name: Install
          command: |
            apt-get update -y && \
            apt-get install -y docker make build-essential 
            make build
